name: CI

on:
  push:
    branches-ignore: [ gh-pages ]
  pull_request:
    branches-ignore: [ gh-pages ]
  #workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    strategy:
      fail-fast: false
      matrix:
        configuration: [ Release, Debug ]
        platform: [ x86, x64 ]
    steps:
      - uses: actions/checkout@v2
#      - uses: NuGet/setup-nuget@v1.0.5
      - uses: microsoft/setup-msbuild@v1
      - name: Build
        run: |
          msbuild /t:restore
          msbuild Open3dmm.sln /m /p:"Configuration=${{ matrix.configuration }};Platform=${{ matrix.platform }}"
      - run: dir
